name = "grant-demo"
main = "worker.js"
compatibility_date = "2024-05-29"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
USER_HASHES = '{"admin":{"salt":"<salt>","hash":"<bcrypt hash>"},"user":{"salt":"<salt>","hash":"<bcrypt hash>"}}'

[[d1_databases]]
binding = "DB"
database_name = "EQORE_DB"
database_id = "85970bbc-3d0b-4922-8ec2-3845f4606201"



[[kv_namespaces]]
binding = "USER_PROFILES"
id = "065f64c71e0747079a2e3d86b292770d"





