name = "grant-manager-tool-demo"
main = "worker.js"
compatibility_date = "2024-05-29"
workers_dev = true

[build]
command = "cd ui && npm install && npm run build"

assets = { directory = "ui/dist", not_found_handling = "single-page-application", binding = "ASSETS" }

[[kv_namespaces]]
binding = "USER_PROFILES"
id = "3613c184af7d4890a70f1c9d28583329"

[[kv_namespaces]]
binding = "LOGIN_ATTEMPTS"
id = "713c8d1d9eb34d1ea13656bf40f14ccc"

[[d1_databases]]
binding = "GRANT_MANAGER_DB"
database_name = "grant-manager-db"
database_id = "e99396be-8043-41f6-9762-07c2b6fc4d3f"
migrations_dir = "migrations"

[ai]
binding = "AI"
