name = "grant-demo"
main = "worker/src/worker.ts"
compatibility_date = "2024-05-29"

[build.upload]

[[build.upload.rules]]
globs = ["worker/migrations/*.sql"]
type = "Text"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
USER_HASHES = '{"admin":"713bfda78870bf9d1b261f565286f85e97ee614efe5f0faf7c34e7ca4f65baca","user":"05d49692b755f99c4504b510418efeeeebfd466892540f27acf9a31a326d6504"}'


[[d1_databases]]
binding = "DB"
database_name = "EQORE_DB"
database_id = "85970bbc-3d0b-4922-8ec2-3845f4606201"



[[kv_namespaces]]
binding = "USER_PROFILES"
id = "065f64c71e0747079a2e3d86b292770d"

binding = "LOGIN_ATTEMPTS",
id = "65e462c43a2046e5bbb95391c2a6e6e9"



[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "pdf-bucket"

[[queues.consumers]]
queue = "PDF_INGEST"
service = "pdf-worker"
binding = "PDF_INGEST"

[[queues.producers]]
queue = "SCORE_QUEUE"
binding = "SCORE_QUEUE"


[[migrations_dir]]


