-- v3: Seed curated non-governmental (foundation / corporate / community) grants.
-- source_channel values used here: 'foundation', 'corporate', 'community_foundation'
-- These rows are manually curated; re-running is safe (ON CONFLICT(name) DO UPDATE).

INSERT INTO programs (
  type, name, sponsor, source_url,
  region_eligibility, deadline, cadence, benefits,
  eligibility_conditions, stage, non_dilutive, stack_required,
  relevance, fit, ease, weighted_score, notes,
  award_ceiling, award_floor, source_channel
) VALUES

-- ── Energy & Climate ─────────────────────────────────────────────────────────
('Foundation Grant',
 'Energy Foundation General Support',
 'Energy Foundation',
 'https://www.ef.org/what-we-fund/',
 'US-based nonprofits',
 'Rolling',
 'Annual',
 'Up to $500,000',
 'Nonprofits working on clean energy transition, climate policy, or equitable energy access',
 'Established Program',
 1, 0, 2.5, 2.5, 2.0, 2.4, '',
 500000, NULL, 'foundation'),

('Foundation Grant',
 'Kresge Foundation Climate Change Initiative',
 'Kresge Foundation',
 'https://kresge.org/programs/environment/',
 'US-based nonprofits and cooperatives',
 'Rolling — Letter of Inquiry',
 'Annual',
 '$50,000 – $500,000',
 '501(c)(3) organizations focused on climate resilience, environmental justice, or clean energy in underserved communities',
 'Established Program',
 1, 0, 3.0, 2.5, 1.5, 2.5, '',
 500000, 50000, 'foundation'),

('Foundation Grant',
 'Robert Wood Johnson Foundation Health & Climate',
 'Robert Wood Johnson Foundation',
 'https://www.rwjf.org/en/grants/funding-opportunities.html',
 'US nonprofits and research institutions',
 'Rolling — by invitation',
 'Annual',
 '$100,000 – $1,000,000',
 'Organizations connecting climate change to community health, with focus on BIPOC and low-income communities',
 'Established Program',
 1, 0, 2.0, 2.0, 1.5, 1.9, '',
 1000000, 100000, 'foundation'),

-- ── Cooperative Economics & Community Wealth ──────────────────────────────────
('Foundation Grant',
 'Cooperative Development Foundation Grant Program',
 'Cooperative Development Foundation',
 'https://www.cdf.coop/grant-programs',
 'US cooperative businesses and support organizations',
 'Varies by program cycle',
 'Annual',
 '$5,000 – $25,000',
 'Worker, consumer, housing, or agricultural cooperatives; co-op development technical assistance organizations',
 'Pilot / Proof of Concept',
 1, 0, 3.0, 3.0, 2.5, 2.9, '',
 25000, 5000, 'foundation'),

('Foundation Grant',
 'Democracy at Work Institute (DAWI) Cooperative Grants',
 'Democracy at Work Institute',
 'https://institute.coop/grants',
 'US worker cooperatives and co-op converters',
 'Rolling',
 'Annual',
 '$10,000 – $50,000',
 'Worker-owned cooperatives, especially those serving BIPOC workers or converting from conventional ownership',
 'Pilot / Proof of Concept',
 1, 0, 3.0, 3.0, 2.5, 2.9, '',
 50000, 10000, 'foundation'),

('Foundation Grant',
 'MacArthur Foundation — Economic Justice',
 'John D. and Catherine T. MacArthur Foundation',
 'https://www.macfound.org/programs/economic-justice/',
 'US nonprofits',
 'By invitation — submit Expression of Interest',
 'Annual',
 '$100,000 – $500,000',
 'Organizations advancing economic equity, worker ownership, or systemic wealth-building strategies',
 'Established Program',
 1, 0, 2.5, 2.0, 1.0, 2.0, '',
 500000, 100000, 'foundation'),

-- ── Food Sovereignty & Agriculture ───────────────────────────────────────────
('Foundation Grant',
 'W.K. Kellogg Foundation Food & Community',
 'W.K. Kellogg Foundation',
 'https://www.wkkf.org/what-we-do/food-and-community',
 'US nonprofits; priority to communities of color',
 'Rolling — Letter of Inquiry',
 'Annual',
 '$25,000 – $250,000',
 'Organizations supporting food systems change, food sovereignty, or community-controlled food access for BIPOC communities',
 'Established Program',
 1, 0, 2.5, 2.5, 1.5, 2.3, '',
 250000, 25000, 'foundation'),

('Foundation Grant',
 'Jessie Smith Noyes Foundation — Food Systems',
 'Jessie Smith Noyes Foundation',
 'https://noyes.org/grantmaking/food-systems/',
 'US nonprofits',
 'Rolling',
 'Annual',
 '$20,000 – $75,000',
 'Grassroots organizations working on organic agriculture, local food systems, and food sovereignty',
 'Pilot / Proof of Concept',
 1, 0, 2.5, 2.0, 2.5, 2.3, '',
 75000, 20000, 'foundation'),

-- ── Housing & Community Development ─────────────────────────────────────────
('Foundation Grant',
 'NeighborWorks America Grants',
 'NeighborWorks America',
 'https://www.neighborworks.org/Funding-Opportunities',
 'NeighborWorks network members; community-based organizations',
 'Annual cycle — check site for dates',
 'Annual',
 '$10,000 – $100,000',
 'Nonprofits focused on affordable housing, community development, or financial stability for low-income residents',
 'Established Program',
 1, 0, 2.0, 2.0, 2.0, 2.0, '',
 100000, 10000, 'foundation'),

('Foundation Grant',
 'Local Initiatives Support Corporation (LISC) Community Grants',
 'LISC',
 'https://www.lisc.org/our-resources/resource/grants-loans/',
 'US CDFIs and community development organizations',
 'Rolling',
 'Rolling',
 '$25,000 – $250,000',
 'CDFIs, community land trusts, and nonprofits focused on affordable housing, economic development, or financial inclusion',
 'Established Program',
 1, 0, 2.0, 2.0, 2.0, 2.0, '',
 250000, 25000, 'foundation'),

-- ── Solar & Clean Energy Workforce ───────────────────────────────────────────
('Foundation Grant',
 'Schmidt Futures Energy Equity Initiative',
 'Schmidt Futures',
 'https://www.schmidtfutures.com/our-work/energy/',
 'US nonprofits and research institutions',
 'By invitation — submit inquiry',
 'Annual',
 '$50,000 – $500,000',
 'Organizations advancing clean energy access, workforce development in clean energy, or energy equity for underserved communities',
 'Established Program',
 1, 0, 3.0, 2.5, 1.5, 2.5, '',
 500000, 50000, 'foundation'),

('Foundation Grant',
 'Tides Foundation — Clean Energy & Just Transition',
 'Tides Foundation',
 'https://www.tides.org/philanthropy-services/grantmaking/',
 'US nonprofits and fiscally-sponsored projects',
 'Rolling',
 'Rolling',
 '$10,000 – $100,000',
 'Grassroots and community-led clean energy initiatives, especially those centering frontline communities in the just transition',
 'Pilot / Proof of Concept',
 1, 0, 3.0, 2.5, 2.0, 2.7, '',
 100000, 10000, 'foundation'),

-- ── Arts, Media & Civic Tech ──────────────────────────────────────────────────
('Foundation Grant',
 'Mozilla Foundation Technology & Society Grants',
 'Mozilla Foundation',
 'https://foundation.mozilla.org/en/what-we-fund/grants/',
 'Global, US preferred',
 'Annual open call',
 'Annual',
 '$25,000 – $150,000',
 'Organizations building open-source civic technology, digital rights tools, or community-controlled tech infrastructure',
 'Pilot / Proof of Concept',
 1, 0, 2.5, 2.5, 2.0, 2.4, '',
 150000, 25000, 'foundation'),

('Foundation Grant',
 'Sundance Institute Documentary Fund',
 'Sundance Institute',
 'https://www.sundance.org/programs/documentary-film/',
 'US and international independent filmmakers',
 'Annual — check sundance.org for cycle dates',
 'Annual',
 '$10,000 – $50,000',
 'Independent documentary filmmakers; priority to underrepresented voices and social-impact storytelling',
 'Pilot / Proof of Concept',
 1, 0, 2.0, 2.0, 2.0, 2.0, '',
 50000, 10000, 'foundation'),

('Foundation Grant',
 'Open Society Foundations — Economic Justice',
 'Open Society Foundations',
 'https://www.opensocietyfoundations.org/grants',
 'US and international nonprofits',
 'By invitation',
 'Annual',
 '$50,000 – $500,000',
 'Organizations advancing economic rights, worker power, racial justice, or civic participation',
 'Established Program',
 1, 0, 2.5, 2.0, 1.0, 2.0, '',
 500000, 50000, 'foundation'),

-- ── Corporate & Community Foundation ─────────────────────────────────────────
('Corporate Grant',
 'Google.org Impact Challenge: Community',
 'Google.org',
 'https://www.google.org/impact-challenge/',
 'US nonprofits (city/region varies by cycle)',
 'Annual open call',
 'Annual',
 '$100,000 – $1,000,000',
 '501(c)(3) nonprofits using technology or data to solve community challenges; equity and inclusion lens required',
 'Pilot / Proof of Concept',
 1, 0, 2.0, 2.0, 2.0, 2.0, '',
 1000000, 100000, 'corporate'),

('Corporate Grant',
 'Wells Fargo Foundation — Housing Affordability',
 'Wells Fargo Foundation',
 'https://www.wellsfargo.com/about/corporate-responsibility/community-giving/',
 'US nonprofits and CDFIs',
 'Rolling',
 'Rolling',
 '$10,000 – $250,000',
 'Community development organizations, affordable housing developers, and CDFIs focused on homeownership or renter stability',
 'Established Program',
 1, 0, 1.5, 1.5, 2.5, 1.7, '',
 250000, 10000, 'corporate'),

('Community Foundation Grant',
 'Boston Foundation — Community Grants',
 'The Boston Foundation',
 'https://www.tbf.org/tbf/71/grants',
 'Greater Boston nonprofits',
 'Annual cycle — see tbf.org',
 'Annual',
 '$10,000 – $75,000',
 'Boston-area nonprofits addressing economic opportunity, housing, education, or community health; strong equity focus',
 'Established Program',
 1, 0, 2.5, 2.5, 2.5, 2.5, '',
 75000, 10000, 'community_foundation'),

('Community Foundation Grant',
 'Highland Street Foundation — Boston Community',
 'Highland Street Foundation',
 'https://www.highlandstreet.org/grant-programs/',
 'Greater Boston nonprofits',
 'Annual — spring cycle',
 'Annual',
 '$5,000 – $50,000',
 'Boston-area nonprofits serving youth, workforce development, or community enrichment',
 'Pilot / Proof of Concept',
 1, 0, 2.0, 2.0, 2.5, 2.1, '',
 50000, 5000, 'community_foundation')

ON CONFLICT(name) DO UPDATE SET
  type                  = excluded.type,
  sponsor               = excluded.sponsor,
  source_url            = excluded.source_url,
  region_eligibility    = excluded.region_eligibility,
  deadline              = excluded.deadline,
  cadence               = excluded.cadence,
  benefits              = excluded.benefits,
  eligibility_conditions = excluded.eligibility_conditions,
  stage                 = excluded.stage,
  non_dilutive          = excluded.non_dilutive,
  award_ceiling         = excluded.award_ceiling,
  award_floor           = excluded.award_floor,
  source_channel        = excluded.source_channel;
