# wrangler.toml (wrangler v3.88.0^)

name = "grant-demo"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "GRANT_MANAGER_DB"
database_id = "your-d1-database-id-here"

[site]
bucket = "./public"

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "pdf-bucket"
preview_bucket_name = "pdf-bucket"

[[services]]
binding = "PDF_WORKER"
service = "pdf-worker"

[[kv_namespaces]]
binding = "LOGIN_ATTEMPTS"
id = "713c8d1d9eb34d1ea13656bf40f14ccc"

[[kv_namespaces]]
binding = "USER_PROFILES"
id = "3613c184af7d4890a70f1c9d28583329"

