# wrangler.toml (wrangler v3.88.0^)

name = "grant-demo"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[site]
bucket = "./public"

[observability.logs]
enabled = false



[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "pdf-bucket"
preview_bucket_name = "pdf-bucket"


