# wrangler.toml (wrangler v3.88.0^)

name = "grant-demo"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[site]
bucket = "./public"

[observability.logs]
enabled = false

[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "PDF_BUCKET"

[[queues.consumers]]
queue = "PDF_INGEST"
script = "pdf-worker"

[workers.pdf-worker]
main = "src/pdf_worker.ts"



