# wrangler.toml (wrangler v3.88.0^)

name = "grant-demo"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[[d1_databases]]
binding = "DB"
database_name = "EQORE_DB"
database_id = "EQORE_DB"

[site]
bucket = "./public"

[observability.logs]
enabled = false



