# wrangler.toml (wrangler v3.88.0^)

name = "grant-demo"
main = "src/worker.ts"
compatibility_date = "2024-05-29"

[[d1_databases]]
binding = "DB"
database_name = "EQORE_DB"
database_id = "85970bbc-3d0b-4922-8ec2-3845f4606201"

[site]
bucket = "./public"

[observability.logs]
enabled = false

[[r2_buckets]]
binding = "PDF_BUCKET"
bucket_name = "pdf-bucket"
preview_bucket_name = "pdf-bucket"

[[queues.consumers]]
queue = "PDF_INGEST"
service = "pdf-worker"

[services]
main = "src/pdf_worker.ts"
